---
- name: Configure Docker on EC2 Instances
  hosts: hostserver
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Install Docker
      apt:
        name: docker.io=26.1.3-0ubuntu1~24.04.1
        state: present
      when: docker_installed.rc != 0

    - name: Deploy Docker Container
      command: docker run -itd -p 9090:8082 --name healthcare thousifahamed/healthcare:v2





