
- name: Configure Docker on EC2 Instances
  hosts: hostserver
  become: yes
  connection: ssh

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      command: docker run -itd -p 9090:8082 --name healthcare_v2 thousifahamed/healthcare:latest

   - name: Remove existing healthcare_v2 container (if any)
     command: docker rm -f healthcare_v2
     ignore_errors: yes

  - name: Deploy Docker Container
    command: docker run -itd -p 9090:8082 --name healthcare_v2 thousifahamed/healthcare:latest




