
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
        - name: capstone-app-container
          image: thousifahamed/healthcare:latest
          ports:
            - containerPort: 8082  # Fixed to match the targetPort in the service

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: NodePort
  selector:
    app: healthcare-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8082  # Should match the containerPort in Deployment
      nodePort: 30082  # Exposed NodePort
      - name: Deploy Docker Container
  docker_container:
    name: healthcare_v2
    image: thousifahamed/healthcare:latest
    state: started
    restart_policy: always
    ports:
      - "9090:8082"

